spring:
  profiles:
    group:
      "local": "default,local"
      "dev": "default,dev"
      "prod": "default,prod"
    active: local

---
spring:
  config:
    activate:
      on-profile: "default"
  application:
    name: rgb-team

server:
  port: 8080

springdoc:
  api-docs:
    groups:
      enabled: true
  swagger-ui:
    path: /swagger-ui.html
    displayRequestDuration: true
    groups-order: DESC
---
spring:
  config:
    activate:
      on-profile: local
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: "jdbc:h2:mem:~/test;MODE=postgresql"
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    database: h2
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        show_sql: true
        format_sql: true
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://10.10.34.130:30507/postgres
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: validate
    database: postgresql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        format_sql: true